# Generated by Django 3.2.4 on 2021-06-11 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210611_1908'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parametros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plano_mes', models.BooleanField(null=True, verbose_name='Plano Mensal R$ 50,00')),
                ('plano_tri', models.BooleanField(null=True, verbose_name='Plano Trimestral R$ 130,00')),
            ],
        ),
    ]
