# Generated by Django 3.2.4 on 2021-06-11 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_parametros'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoa',
            name='plano_mes',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='plano_tri',
        ),
    ]
