# Generated by Django 3.2.4 on 2021-06-11 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210611_1924'),
    ]

    operations = [
        migrations.CreateModel(
            name='FichaPessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.DecimalField(decimal_places=2, max_digits=6)),
                ('altura', models.DecimalField(decimal_places=2, max_digits=6)),
                ('imc', models.DecimalField(decimal_places=2, max_digits=6)),
                ('data_inicio', models.DateField()),
                ('observacoes', models.TextField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pessoa')),
            ],
        ),
    ]
