# Generated by Django 3.2.4 on 2021-06-12 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210611_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichapessoa',
            name='idade',
            field=models.CharField(default=1, max_length=3),
            preserve_default=False,
        ),
    ]
