# Generated by Django 3.2.4 on 2021-06-12 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_fichapessoa_idade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichapessoa',
            name='idade',
            field=models.IntegerField(max_length=3),
        ),
    ]
