# Generated by Django 3.2.4 on 2021-06-12 01:09
import datetime
from django.utils import timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_fichapessoa_idade'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='data_nascimento',
            field=models.DateField(default= timezone.now, verbose_name='Data de nascimento'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fichapessoa',
            name='idade',
            field=models.IntegerField(),
        ),
    ]
