# Generated by Django 3.2.4 on 2021-06-12 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20210611_2209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoa',
            name='data_nascimento',
        ),
    ]
