# Generated by Django 3.2.4 on 2021-06-12 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_pessoa_data_nascimento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fichapessoa',
            name='data_inicio',
        ),
    ]
