# Generated by Django 3.2.4 on 2021-06-12 01:31
from django.utils import timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_fichapessoa_data_inicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichapessoa',
            name='data_inicio',
            field=models.DateField(u'Data do inicio das atividades'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pessoa',
            name='data_nascimento',
            field=models.DateField(default= timezone.now, verbose_name='Data de nascimento'),
            preserve_default=False,
        ),
    ]
