# Generated by Django 3.2.4 on 2021-06-12 02:04
from django.utils import timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20210611_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='data_nascimento',
            field=models.DateField(default= timezone.now, verbose_name='data de nascimento'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fichapessoa',
            name='data_inicio',
            field=models.DateField(default= timezone.now, verbose_name='Inicio das atividades'),
        ),
    ]
