# Generated by Django 3.2.4 on 2021-06-12 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20210611_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichapessoa',
            name='sexo',
            field=models.CharField(choices=[('F', 'Feminino'), ('M', 'Masculino')], default=str, max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fichapessoa',
            name='data_inicio',
            field=models.DateField(verbose_name='Inicio das atividades'),
        ),
    ]
