# Generated by Django 3.2.4 on 2021-06-12 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20210611_2319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoa',
            name='plano_mes',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='plano_tri',
        ),
        migrations.AddField(
            model_name='pessoa',
            name='plano',
            field=models.CharField(choices=[('M', 'Mensal'), ('T', 'Trimestral')], default=str, max_length=1),
            preserve_default=False,
        ),
    ]
