# Generated by Django 3.2.4 on 2021-06-12 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20210611_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='plano',
            field=models.CharField(choices=[('M', 'Mensal R$ 50,00'), ('T', 'Trimestral R$ 130,00')], max_length=1),
        ),
    ]
