# Generated by Django 3.2.4 on 2021-06-12 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_pessoa_plano'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichapessoa',
            name='peso',
            field=models.DecimalField(decimal_places=3, max_digits=6),
        ),
    ]
