# Generated by Django 3.2.4 on 2021-06-12 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20210612_0916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoa',
            name='meu_campo_obrigatorio',
        ),
    ]
