# Generated by Django 3.2.4 on 2021-06-12 12:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_remove_pessoa_meu_campo_obrigatorio'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='horario_registro',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
