# Generated by Django 3.2.4 on 2021-06-12 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_auto_20210612_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='plano',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.plano'),
        ),
    ]
