# Generated by Django 3.2.4 on 2021-06-12 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_pessoa_plano'),
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rua', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='endereco',
        ),
    ]
