# Generated by Django 3.2.4 on 2021-06-12 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_auto_20210612_1028'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50)),
                ('tipo', models.CharField(choices=[('RG', 'Carteira de identidade'), ('CPF', 'Cadastro unico de pessoa fisica (CPF)'), ('PP', 'Passaporte')], max_length=3)),
                ('pessoa', models.OneToOneField(help_text='Pessoa', on_delete=django.db.models.deletion.CASCADE, to='core.pessoa')),
            ],
        ),
    ]
